version: "3.8"
services:
  backend:
    build:
      context: .
      args:
        INSTALL_PLAYWRIGHT: "false"
    environment:
      - FIREBASE_CREDENTIALS=${FIREBASE_CREDENTIALS}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - EMAIL_FROM=${EMAIL_FROM}
      - BACKEND_URL=${BACKEND_URL}
      - USE_PLAYWRIGHT=${USE_PLAYWRIGHT}
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
